# Generated by Django 5.1.1 on 2024-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_date', models.DateField()),
                ('reg_no', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('sub_location', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
            ],
        ),
    ]
