# Generated by Django 5.1.1 on 2024-09-14 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community_health_promoter", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chp",
            name="user_id",
        ),
    ]
