# Generated by Django 5.1.1 on 2024-10-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_health_promoter', '0002_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chp',
            old_name='registered_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chp',
            name='hospital',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
