# Generated by Django 5.1.1 on 2024-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_health_promoter", "0004_chp_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
