# Generated by Django 5.1.1 on 2024-09-15 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_health_promoter", "0006_rename_user_id_chp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chp",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
