# Generated by Django 5.1.1 on 2024-09-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_health_promoter', '0006_alter_chp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chp',
            name='email',
        ),
    ]
