# Generated by Django 4.2.16 on 2024-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
