# Generated by Django 4.2.16 on 2024-09-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('admin', 'NurseAdmin'), ('nurse', 'Nurse'), ('chp', 'Community Health Promoter')], max_length=50, null=True),
        ),
    ]
