# Generated by Django 5.1.1 on 2024-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epdsquestion",
            name="question",
            field=models.TextField(unique=True),
        ),
    ]
