# Generated by Django 4.2.16 on 2024-09-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='test_id',
        ),
    ]
