# Generated by Django 4.2.16 on 2024-09-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_answer_test_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
