# Generated by Django 5.0.7 on 2024-09-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mother',
            old_name='mother_id',
            new_name='id',
        ),
    ]
