# Generated by Django 5.0.7 on 2024-09-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0002_rename_mother_id_mother_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='next_of_kin_id',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='next_of_kin_tel',
        ),
    ]
