# Generated by Django 5.1.1 on 2024-10-26 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('mother', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='chp',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'chp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mothers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mother',
            name='hospital',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='sub_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mother',
            name='village',
            field=models.CharField(max_length=255),
        ),
    ]
