# Generated by Django 5.1.1 on 2024-09-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mother", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mother",
            name="no_of_children",
            field=models.PositiveIntegerField(),
        ),
    ]
