# Generated by Django 5.1.1 on 2024-10-01 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='date_of_reg',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
