# Generated by Django 5.1.1 on 2024-09-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0002_alter_mother_no_of_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='date_of_reg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
