# Generated by Django 5.1.1 on 2024-09-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('screeningtestscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.epdsquestion')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screeningtestscore.screeningtestscore')),
            ],
        ),
    ]
