# Generated by Django 5.1.1 on 2024-09-15 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0002_initial"),
        ("questions", "0002_alter_epdsquestion_question"),
        ("screeningtestscore", "0002_rename_chp_id_screeningtestscore_chp_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "test")},
        ),
    ]
