# Generated by Django 5.1.1 on 2024-09-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
