# Generated by Django 5.1.1 on 2024-09-21 05:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careguide',
            fields=[
                ('careguide_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='caregude_images/')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
