# Generated by Django 5.1.1 on 2024-09-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careguide', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Careguide',
        ),
    ]
