# Generated by Django 5.1.1 on 2024-10-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careguide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careguide',
            name='image',
            field=models.URLField(blank=True, max_length=253),
        ),
        migrations.AlterField(
            model_name='careguide',
            name='subtitle',
            field=models.CharField(max_length=253),
        ),
        migrations.AlterField(
            model_name='careguide',
            name='title',
            field=models.CharField(max_length=253),
        ),
    ]
