# Generated by Django 5.1.1 on 2024-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careguide', '0002_rename_resources_careguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='careguide',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
