# Generated by Django 5.1.1 on 2024-09-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careguide', '0002_alter_careguide_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careguide',
            old_name='careguide_id',
            new_name='id',
        ),
    ]
