# Generated by Django 5.1.1 on 2024-09-09 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CHP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_date', models.DateField()),
                ('bio_description', models.TextField()),
                ('reg_no', models.CharField(max_length=255)),
                ('number_of_assigned_mothers', models.IntegerField()),
                ('location', models.TextField()),
                ('sub_location', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
