# Generated by Django 5.1.1 on 2024-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_health_promoter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chp',
            name='bio_description',
        ),
        migrations.RemoveField(
            model_name='chp',
            name='number_of_assigned_mothers',
        ),
        migrations.AddField(
            model_name='chp',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
