# Generated by Django 5.1.1 on 2024-09-21 05:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('tel_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be between 10 and 15 digits and start with '+' if international.", regex='^\\+?\\d{10,15}$')])),
                ('reg_no', models.CharField(max_length=50)),
                ('sub_location', models.CharField(max_length=255)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
