# Generated by Django 5.1.1 on 2024-09-14 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nurse",
            old_name="user",
            new_name="user_id",
        ),
    ]
