# Generated by Django 5.1.1 on 2024-09-15 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0003_rename_user_nurse_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nurse",
            old_name="user_id",
            new_name="user",
        ),
    ]
