# Generated by Django 5.1.1 on 2024-09-15 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0004_rename_user_id_nurse_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurse",
            name="tel_no",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be between 10 and 15 digits and start with '+' if international.",
                        regex="^\\+?\\d{10,15}$",
                    )
                ],
            ),
        ),
    ]
