# Generated by Django 5.1.1 on 2024-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
