# Generated by Django 5.1.1 on 2024-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningTestScore',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField()),
                ('total_score', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
