# Generated by Django 5.1.1 on 2024-09-15 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screeningtestscore", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screeningtestscore",
            old_name="chp_id",
            new_name="chp",
        ),
        migrations.RenameField(
            model_name="screeningtestscore",
            old_name="mother_id",
            new_name="mother",
        ),
    ]
