# Generated by Django 5.1.1 on 2024-10-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeningtestscore',
            old_name='test_id',
            new_name='id',
        ),
    ]
