# Generated by Django 5.1.1 on 2024-09-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screeningtestscore", "0002_rename_chp_id_screeningtestscore_chp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screeningtestscore",
            name="total_score",
            field=models.IntegerField(),
        ),
    ]
