# Generated by Django 5.1.1 on 2024-09-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0004_rename_test_id_screeningtestscore_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeningtestscore',
            old_name='id',
            new_name='test_id',
        ),
    ]
