# Generated by Django 5.1.1 on 2024-09-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0005_rename_chp_screeningtestscore_chp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeningtestscore',
            old_name='mothe_id',
            new_name='mother_id',
        ),
    ]
