# Generated by Django 5.1.1 on 2024-10-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0002_rename_test_id_screeningtestscore_id'),
        ('screeningtestscore', '0006_rename_test_id_screeningtestscore_id'),
    ]

    operations = [
    ]
