<<<<<<< Updated upstream:screeningtestscore/migrations/0008_rename_test_id_screeningtestscore_id.py
# Generated by Django 5.1.1 on 2024-10-03 16:15
=======
# Generated by Django 5.1.1 on 2024-10-04 07:34
>>>>>>> Stashed changes:screeningtestscore/migrations/0002_rename_test_id_screeningtestscore_id.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0007_merge_20241003_1611'),
    ]

    operations = [
<<<<<<< Updated upstream:screeningtestscore/migrations/0008_rename_test_id_screeningtestscore_id.py
        
=======
        migrations.RenameField(
            model_name='screeningtestscore',
            old_name='test_id',
            new_name='id',
        ),
>>>>>>> Stashed changes:screeningtestscore/migrations/0002_rename_test_id_screeningtestscore_id.py
    ]
