# Generated by Django 5.1.1 on 2024-10-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0007_merge_20241003_1611'),
    ]

    operations = [
        
    ]
