# Generated by Django 5.1.1 on 2024-10-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0008_rename_test_id_screeningtestscore_id'),
    ]

    operations = [
        
    ]
