
# Generated by Django 5.1.1 on 2024-10-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeningtestscore', '0009_rename_test_id_screeningtestscore_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeningtestscore',
            old_name='test_id',
            new_name='id',
        ),
    ]
