# Generated by Django 5.1.1 on 2024-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_admin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
