# Generated by Django 5.1.1 on 2024-09-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_admin', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseadmin',
            old_name='admin_id',
            new_name='id',
        ),
    ]
