# Generated by Django 5.1.1 on 2024-10-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_admin', '0003_alter_nurseadmin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseadmin',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.AddField(
            model_name='nurseadmin',
            name='village',
            field=models.CharField(default='Village', max_length=255),
        ),
    ]
